// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkdOJ1EMLNtwUDt1xpzDDFzBERd4zWAek',
    appId: '1:895990217257:android:d139bfabd5decc61a2ba38',
    messagingSenderId: '895990217257',
    projectId: 'diaryapp-93501',
    databaseURL: 'https://diaryapp-93501-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'diaryapp-93501.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgeduyhc1GBkcgcI5vo1nTa3uKhhmra7o',
    appId: '1:895990217257:ios:f99e50371119d22ba2ba38',
    messagingSenderId: '895990217257',
    projectId: 'diaryapp-93501',
    databaseURL: 'https://diaryapp-93501-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'diaryapp-93501.appspot.com',
    androidClientId: '895990217257-94ltttkvur4l925omh97jklpne1f51in.apps.googleusercontent.com',
    iosClientId: '895990217257-6clntri71akna4nofv7ti5bcuem7ogsm.apps.googleusercontent.com',
    iosBundleId: 'com.example.diaryapp',
  );
}
